/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Has_A.Client;
import Interface.OnlinePlayable;
import MainAndSys.VideogameSys;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ahmet
 */
public class VideoGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form VideoGameFrame
     */
    public static ArrayList<Client> clients = new ArrayList<>();
    public SearchFrame sf = new SearchFrame();
    public DisplayFrame df = new DisplayFrame();
    
    public void clear() {
        getName.setText("");
        getPublisher.setText("");
        getYear.setText("");
        getType.setText("");
        getModel.setText("");
        getLimit.setText("");        
        getmGPU.setText("");
        getmRAM.setText("");
        getmCPU.setText("");
        getmOS.setText("");       
    }
    
    public VideoGameFrame() {
        initComponents();
        if (pcGame.isSelected()) {
            PCVideoGameP.setVisible(true);
            ConsolVideoGameP.setVisible(false);
        } else {
            PCVideoGameP.setVisible(false);
            ConsolVideoGameP.setVisible(true);
        }
    }
    
    public void fillCombobox() {
        sf.getTitleCMB().setModel(new DefaultComboBoxModel(VideogameSys.getVideogameList()));
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        TypePanel = new javax.swing.JPanel();
        ConsolVideoGameP = new javax.swing.JPanel();
        model = new javax.swing.JLabel();
        getModel = new javax.swing.JTextField();
        limit = new javax.swing.JLabel();
        getLimit = new javax.swing.JTextField();
        exclusive = new javax.swing.JCheckBox();
        cOnline = new javax.swing.JCheckBox();
        cCoop = new javax.swing.JCheckBox();
        PCVideoGameP = new javax.swing.JPanel();
        mGPU = new javax.swing.JLabel();
        getmGPU = new javax.swing.JTextField();
        getmRAM = new javax.swing.JTextField();
        getmCPU = new javax.swing.JTextField();
        mCPU = new javax.swing.JLabel();
        mRAM = new javax.swing.JLabel();
        mOS = new javax.swing.JLabel();
        getmOS = new javax.swing.JTextField();
        pcOnline = new javax.swing.JCheckBox();
        pcCoop = new javax.swing.JCheckBox();
        VGname = new javax.swing.JLabel();
        VGpublisher = new javax.swing.JLabel();
        VGyear = new javax.swing.JLabel();
        VGtype = new javax.swing.JLabel();
        getName = new javax.swing.JTextField();
        getPublisher = new javax.swing.JTextField();
        getYear = new javax.swing.JTextField();
        getType = new javax.swing.JTextField();
        pcGame = new javax.swing.JRadioButton();
        cGame = new javax.swing.JRadioButton();
        clientP = new javax.swing.JPanel();
        cName = new javax.swing.JLabel();
        cType = new javax.swing.JLabel();
        getcName = new javax.swing.JTextField();
        getcType = new javax.swing.JTextField();
        cAdd = new javax.swing.JButton();
        addVideoGame = new javax.swing.JButton();
        displayClients = new javax.swing.JButton();
        searchVideoGame = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        info = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TypePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConsolVideoGameP.setBorder(javax.swing.BorderFactory.createTitledBorder("Consol Video Game"));

        model.setText("Console Model :");

        limit.setText("Player Limit :");

        exclusive.setText("Exclusive Game");

        cOnline.setText("Online Playable");

        cCoop.setText("Co-up Playable");

        javax.swing.GroupLayout ConsolVideoGamePLayout = new javax.swing.GroupLayout(ConsolVideoGameP);
        ConsolVideoGameP.setLayout(ConsolVideoGamePLayout);
        ConsolVideoGamePLayout.setHorizontalGroup(
            ConsolVideoGamePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsolVideoGamePLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(model)
                .addGap(10, 10, 10)
                .addComponent(getModel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ConsolVideoGamePLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(limit)
                .addGap(10, 10, 10)
                .addComponent(getLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ConsolVideoGamePLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(exclusive))
            .addGroup(ConsolVideoGamePLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cOnline)
                .addGap(41, 41, 41)
                .addComponent(cCoop))
        );
        ConsolVideoGamePLayout.setVerticalGroup(
            ConsolVideoGamePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsolVideoGamePLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(ConsolVideoGamePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ConsolVideoGamePLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(getModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(ConsolVideoGamePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsolVideoGamePLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(limit))
                    .addComponent(getLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(exclusive)
                .addGap(7, 7, 7)
                .addGroup(ConsolVideoGamePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cOnline)
                    .addComponent(cCoop)))
        );

        TypePanel.add(ConsolVideoGameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 310, 170));
        ConsolVideoGameP.getAccessibleContext().setAccessibleName("PC Video Game");

        PCVideoGameP.setBorder(javax.swing.BorderFactory.createTitledBorder("PC Video Game"));
        PCVideoGameP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGPU.setText("Minimum GPU :");
        PCVideoGameP.add(mGPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 30, 100, -1));
        PCVideoGameP.add(getmGPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, -1));
        PCVideoGameP.add(getmRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, -1));
        PCVideoGameP.add(getmCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 110, -1));

        mCPU.setText("Recommended CPU brand :");
        PCVideoGameP.add(mCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 92, -1, -1));

        mRAM.setText("Minimum RAM :");
        PCVideoGameP.add(mRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 61, -1, -1));

        mOS.setText("Recommended OS :");
        PCVideoGameP.add(mOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 130, -1, -1));
        PCVideoGameP.add(getmOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 110, -1));

        pcOnline.setText("Online Playable");
        PCVideoGameP.add(pcOnline, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        pcCoop.setText("Co-up Playable");
        PCVideoGameP.add(pcCoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        TypePanel.add(PCVideoGameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 190));
        PCVideoGameP.getAccessibleContext().setAccessibleName("Consol Video Game");

        VGname.setText("Video Game Name :");

        VGpublisher.setText("Publisher :");

        VGyear.setText("Year :");

        VGtype.setText("Game Type:");

        buttonGroup1.add(pcGame);
        pcGame.setText("PC Video Game");
        pcGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcGameActionPerformed(evt);
            }
        });

        buttonGroup1.add(cGame);
        cGame.setText("Consol Video Game");
        cGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cGameActionPerformed(evt);
            }
        });

        clientP.setBorder(javax.swing.BorderFactory.createTitledBorder("Client"));

        cName.setText("Name Surname :");

        cType.setText("Client's prefer :");

        cAdd.setText("Add Client");
        cAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientPLayout = new javax.swing.GroupLayout(clientP);
        clientP.setLayout(clientPLayout);
        clientPLayout.setHorizontalGroup(
            clientPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPLayout.createSequentialGroup()
                .addGroup(clientPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientPLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(clientPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(clientPLayout.createSequentialGroup()
                                .addComponent(cType)
                                .addGap(18, 18, 18)
                                .addComponent(getcType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(clientPLayout.createSequentialGroup()
                                .addComponent(cName)
                                .addGap(18, 18, 18)
                                .addComponent(getcName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(clientPLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(cAdd)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        clientPLayout.setVerticalGroup(
            clientPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(clientPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cName)
                    .addComponent(getcName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cType)
                    .addComponent(getcType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cAdd)
                .addGap(5, 5, 5))
        );

        addVideoGame.setText("Add Video Game");
        addVideoGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVideoGameActionPerformed(evt);
            }
        });

        displayClients.setText("Display Clients");
        displayClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayClientsActionPerformed(evt);
            }
        });

        searchVideoGame.setText("Search Video Game");
        searchVideoGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVideoGameActionPerformed(evt);
            }
        });

        message.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        info.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        info.setText("Videogame & Customer Information Save System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VGpublisher)
                            .addComponent(VGname)
                            .addComponent(VGyear)
                            .addComponent(VGtype))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(getPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(getName)
                            .addComponent(getType)
                            .addComponent(getYear))
                        .addGap(18, 18, 18)
                        .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(pcGame)
                        .addGap(31, 31, 31)
                        .addComponent(cGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(addVideoGame)
                                    .addGap(68, 68, 68)
                                    .addComponent(displayClients))
                                .addComponent(clientP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchVideoGame, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(307, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VGname)
                    .addComponent(getName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VGpublisher)
                            .addComponent(getPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VGyear)
                            .addComponent(getYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VGtype)
                            .addComponent(getType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pcGame)
                            .addComponent(cGame)))
                    .addComponent(clientP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVideoGame)
                    .addComponent(displayClients))
                .addGap(27, 27, 27)
                .addComponent(searchVideoGame)
                .addGap(18, 18, 18)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(197, Short.MAX_VALUE)
                    .addComponent(TypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pcGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcGameActionPerformed
        // TODO add your handling code here:
        PCVideoGameP.setVisible(true);
        ConsolVideoGameP.setVisible(false);
    }//GEN-LAST:event_pcGameActionPerformed

    private void cGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cGameActionPerformed
        // TODO add your handling code here:
        ConsolVideoGameP.setVisible(true);
        PCVideoGameP.setVisible(false);
    }//GEN-LAST:event_cGameActionPerformed

    private void cAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAddActionPerformed
        // TODO add your handling code here:
        String name = getcName.getText();
        String whichtype = getcType.getText();
        if (getcName.getText().isEmpty() || getcType.getText().isEmpty()) {
            message.setText("FILL THE CUSTOMER INFORMATIONS.");
        } else {

            name = getcName.getText();
            whichtype = getcType.getText();

            clients.add(new Client(name, whichtype));
            message.setText("CLIENT ADDED.");
            getcName.setText("");
            getcType.setText("");
        }
    }//GEN-LAST:event_cAddActionPerformed

    private void addVideoGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVideoGameActionPerformed
        // TODO add your handling code here:
        if (getName.getText().isEmpty() || getPublisher.getText().isEmpty() || getYear.getText().isEmpty() || getType.getText().isEmpty()) {
            message.setText("DONT LEAVE EMPTY FIELD.");
        } else {
            String name = getName.getText();
            String publisher = getPublisher.getText();
            int year = Integer.parseInt((String)getYear.getText());
            String type = getType.getText();
            if (pcGame.isSelected()) {
                if (getmGPU.getText().isEmpty() || getmRAM.getText().isEmpty() || getmCPU.getText().isEmpty() || getmOS.getText().isEmpty()) {
                    message.setText("DONT LEAVE EMPTY FIELD.");
                } else {
                    int minGPU = Integer.parseInt((String)getmGPU.getText());
                    String brandofCPU = getmCPU.getText();
                    int minRAM = Integer.parseInt((String)getmRAM.getText());                   
                    String minOS = getmOS.getText();                    
                     //if(pcOnline.isSelected())
                        //((OnlinePlayable)OnlinePlayable).setInternetConnection();
                     //if(pcCoop.isSelected())
                        //CoopPlayable.setDeviceConnection();
                    boolean Internetconnection = pcOnline.isSelected();
                    boolean Deviceconnection = pcCoop.isSelected();

                    boolean res = VideogameSys.addPCVideoGame(name, publisher, year, type, clients, Internetconnection, Deviceconnection,
                            minGPU, brandofCPU, minRAM, minOS);

                    if (res) {
                        message.setText("PC VIDEOGAME IS ADDED.");
                    } else {
                        message.setText("PC VIDEOGAME ALREADY EXIST.");
                    }
                }
            } else {
                if (getModel.getText().isEmpty() || getLimit.getText().isEmpty()) {
                    message.setText("DONT LEAVE EMPTY FIELD.");
                } else {                    
                    String consoleType = getModel.getText();
                    int playerLimit = Integer.parseInt((String)getLimit.getText());                
                                  
                    // if(cOnline.isSelected())
                        //OnlinePlayable.setInternetConnection();
                    // if(cCoop.isSelected())
                        //OnlinePlayable.setDeviceConnection();
                    boolean isExclusive = exclusive.isSelected();   
                    boolean Internetconnection = cOnline.isSelected();
                    boolean Deviceconnection = cCoop.isSelected();

                    boolean res = VideogameSys.addConsolVideoGame(name, publisher, year, type, clients, Internetconnection, Deviceconnection
                            ,consoleType, playerLimit, isExclusive);

                    if (res) {
                        message.setText("PC VIDEOGAME IS ADDED.");
                    } else {
                        message.setText("PC VIDEOGAME ALREADY EXIST.");
                    }
                }
            }
            clients.clear();
        }
        VideogameSys.calculatePrice();
    }//GEN-LAST:event_addVideoGameActionPerformed

    private void displayClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayClientsActionPerformed
        // TODO add your handling code here:
        if (VideogameSys.getArrC().isEmpty()) {
            message.setText("LIST IS EMPTY.");
        } else {
            clear();
            df.setVisible(true);
        }
    }//GEN-LAST:event_displayClientsActionPerformed

    private void searchVideoGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVideoGameActionPerformed
        // TODO add your handling code here:
        if (VideogameSys.getArr().isEmpty()) {
            message.setText("LIST IS EMPTY.");
        } else {
            fillCombobox();
            sf.setVisible(true);
        }
    }//GEN-LAST:event_searchVideoGameActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConsolVideoGameP;
    private javax.swing.JPanel PCVideoGameP;
    private javax.swing.JPanel TypePanel;
    private javax.swing.JLabel VGname;
    private javax.swing.JLabel VGpublisher;
    private javax.swing.JLabel VGtype;
    private javax.swing.JLabel VGyear;
    private javax.swing.JButton addVideoGame;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cAdd;
    private javax.swing.JCheckBox cCoop;
    private javax.swing.JRadioButton cGame;
    private javax.swing.JLabel cName;
    private javax.swing.JCheckBox cOnline;
    private javax.swing.JLabel cType;
    private javax.swing.JPanel clientP;
    private javax.swing.JButton displayClients;
    private javax.swing.JCheckBox exclusive;
    private javax.swing.JTextField getLimit;
    private javax.swing.JTextField getModel;
    private javax.swing.JTextField getName;
    private javax.swing.JTextField getPublisher;
    private javax.swing.JTextField getType;
    private javax.swing.JTextField getYear;
    private javax.swing.JTextField getcName;
    private javax.swing.JTextField getcType;
    private javax.swing.JTextField getmCPU;
    private javax.swing.JTextField getmGPU;
    private javax.swing.JTextField getmOS;
    private javax.swing.JTextField getmRAM;
    private javax.swing.JLabel info;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel limit;
    private javax.swing.JLabel mCPU;
    private javax.swing.JLabel mGPU;
    private javax.swing.JLabel mOS;
    private javax.swing.JLabel mRAM;
    private javax.swing.JLabel message;
    private javax.swing.JLabel model;
    private javax.swing.JCheckBox pcCoop;
    private javax.swing.JRadioButton pcGame;
    private javax.swing.JCheckBox pcOnline;
    private javax.swing.JButton searchVideoGame;
    // End of variables declaration//GEN-END:variables
}
